image: Ubuntu2004  
stack: node 19  
branches:
  only:
    - main  

cache: node_modules  

install:
  - yarn install

build: off  

build_script:
  - yarn run build   

test_script:
  - yarn run lint && yarn run test  
  
deploy_script:  
  - git config --global credential.helper store
  - git config --global user.name EvgeniyPryanichnikov
  - git config --global user.email luriro07@icloud.com
  - echo "https://$GITHUB_TOKEN:x-oauth-basic@github.com">"$HOME/.git-credentials"
  - npx push-dir --dir=dist --branch=gh-pages --force --verbose


